
--TEMA 4

--Exercitiul 1



-- a

DECLARE 
  TYPE JOB_RECORD IS RECORD
  ( COD JOBS.JOB_ID%TYPE,
    TITLU JOBS.JOB_TITLE%TYPE,
    SALARIU JOBS.MIN_SALARY%TYPE);
    V_JOB JOB_RECORD;
BEGIN
  V_JOB.COD := 'MY_JOB';
  V_JOB.TITLU := 'Accounting Manager';
  V_JOB.SALARIU := 3000;
  DBMS_OUTPUT.PUT_LINE ('Jobul cu ID-ul: ' || V_JOB.COD || ' are titlul de ' || V_JOB.TITLU|| ' si salariul minim de ' || V_JOB.SALARIU);
   
END;


-- b 


SELECT *
FROM JOBS;
DECLARE 
  TYPE JOB_RECORD IS RECORD
  ( COD JOBS.JOB_ID%TYPE,
    TITLU JOBS.JOB_TITLE%TYPE,
    SALARIU JOBS.MIN_SALARY%TYPE);
    V_JOB JOB_RECORD;
BEGIN
   SELECT JOB_ID, JOB_TITLE, MIN_SALARY
   INTO V_JOB 
   FROM JOBS
   WHERE JOB_ID = 'IT_PROG';
   DBMS_OUTPUT.PUT_LINE ('Jobul cu ID-ul: ' || V_JOB.COD || ' are titlul de ' || V_JOB.TITLU|| ' si salariul minim de ' || V_JOB.SALARIU);
   
END;



--  c

CREATE TABLE JOBS_FLR AS SELECT * FROM JOBS;

ALTER TABLE JOBS_FLR
ADD CONSTRAINT PK_JOBS_FLR PRIMARY KEY (JOB_ID);



SELECT *
FROM JOBS_FLR;

DECLARE 
  TYPE JOB_RECORD IS RECORD
  ( COD JOBS.JOB_ID%TYPE,
    TITLU JOBS.JOB_TITLE%TYPE,
    SALARIU JOBS.MIN_SALARY%TYPE);
    V_JOB JOB_RECORD;
BEGIN
  DELETE FROM JOBS_FLR
  WHERE JOB_ID = 'ST_MAN'
  RETURNING JOB_ID, JOB_TITLE, MIN_SALARY INTO V_JOB;
END;

ROLLBACK;


--Exercitiul 3

SELECT *
FROM DEPT_FLR;



CREATE TABLE DEPT_FLR AS SELECT * FROM DEPARTMENTS;

ALTER TABLE DEPT_FLR 
ADD CONSTRAINT PK_DEPT_FLR PRIMARY KEY(DEPARTMENT_ID);


--a

DECLARE
   V_DEPT1 DEPT_FLR%ROWTYPE;
   V_DEPT2 DEPT_FLR%ROWTYPE;
BEGIN
    V_DEPT1.DEPARTMENT_ID := 300;
    V_DEPT1.DEPARTMENT_NAME := 'Research';
    V_DEPT1.MANAGER_ID := 103;
    V_DEPT1.LOCATION_ID :=1700;
    
    INSERT INTO DEPT_FLR VALUES V_DEPT1;
    

        
END;

ROLLBACK;
--b

DECLARE
   V_DEPT1 DEPT_FLR%ROWTYPE;
   V_DEPT2 DEPT_FLR%ROWTYPE;
BEGIN

    DELETE FROM DEPT_FLR
    WHERE DEPARTMENT_ID = 50
    RETURNING DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID  INTO V_DEPT2;
    DBMS_OUTPUT.PUT_LINE('Departamentul sters anterior are ID-ul ' || V_DEPT2.DEPARTMENT_ID || ' , numele ' || V_DEPT2.DEPARTMENT_NAME || ' si locatia ' || V_DEPT2.LOCATION_ID );
        
END;

ROLLBACK;

--Exercitiul 2
DECLARE 
  V_EMP1 EMP_FLR%ROWTYPE;
  V_EMP2 EMP_FLR%ROWTYPE;
  
BEGIN

SELECT *
FROM EMP_FLR
WHERE SALARY = (SELECT MAX(SALARY)
                FROM EMP_FLR)
AND ROWNUM < 2;

SELECT *
INTO V_EMP2
FROM EMP_FLR
WHERE SALARY = (SELECT MIN(SALARY)
                FROM EMP_FLR);

END;
  


             